### ISSUE TITLE
mesutBE: Deploying Heroku - throw new ERR_INVALID_ARG_TYPE(name, 'string', value)

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#371]
Hi @colevandersWands, @sjimi,
I am getting an error after deploying my app with `heroku`.

![Screenshot from 2020-06-01 16-26-52](https://user-images.githubusercontent.com/59531743/83419626-a2c84300-a425-11ea-84ce-a0aa97da9e66.png)

I couldn't find anything to solve. Please helppp!

[here](https://github.com/MesutBE/courses-web-app) is my project repo.
[here](https://github.com/MesutBE/courses-web-app/tree/master/config) is my config file.

Here is my local folder view..
![Screenshot from 2020-06-01 16-32-26](https://user-images.githubusercontent.com/59531743/83419534-7f9d9380-a425-11ea-9b54-fe178ec317d0.png)
 
here is the log file for the error...

```javascript

2020-06-01T14:24:57.178108+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-01T14:25:01.869016+00:00 heroku[web.1]: Starting process with command `node index.js`
2020-06-01T14:25:03.507572+00:00 app[web.1]: internal/validators.js:120
2020-06-01T14:25:03.507587+00:00 app[web.1]: throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
2020-06-01T14:25:03.507591+00:00 app[web.1]: ^
2020-06-01T14:25:03.507591+00:00 app[web.1]: 
2020-06-01T14:25:03.507605+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
2020-06-01T14:25:03.507606+00:00 app[web.1]: at validateString (internal/validators.js:120:11)
2020-06-01T14:25:03.507606+00:00 app[web.1]: at Object.join (path.js:1039:7)
2020-06-01T14:25:03.507607+00:00 app[web.1]: at Object.<anonymous> (/app/api/controllers.js:9:23)
2020-06-01T14:25:03.507607+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-01T14:25:03.507608+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-06-01T14:25:03.507609+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:986:32)
2020-06-01T14:25:03.507609+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-06-01T14:25:03.507609+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1026:19)
2020-06-01T14:25:03.507610+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-01T14:25:03.507610+00:00 app[web.1]: at Object.<anonymous> (/app/api/routes.js:1:21) {
2020-06-01T14:25:03.507610+00:00 app[web.1]: code: 'ERR_INVALID_ARG_TYPE'
2020-06-01T14:25:03.507611+00:00 app[web.1]: }
2020-06-01T14:25:03.568214+00:00 heroku[web.1]: Process exited with status 1
2020-06-01T14:25:03.602302+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-01T14:25:23.109136+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=courses-web-app-m.herokuapp.com request_id=c1d73341-29fe-4cf1-bfbc-702b8e81ac90 fwd="84.198.24.12" dyno= connect= service= status=503 bytes= protocol=https
```

![Screenshot from 2020-06-01 16-25-55](https://user-images.githubusercontent.com/59531743/83418943-a0b1b480-a424-11ea-9ae0-c6174c9d191c.png)

**Comment by MesutBE** [comment]
Finally I solve the problem..

I changed the line below with the line below it..
```javascript
const DATA_DIR = path.join(__dirname, '..', config.DATA_DIR, 'data/courses.json');

const DATA_DIR = path.join(__dirname, '..', 'data/courses.json');
```
see the link below..
https://github.com/MesutBE/courses-web-app/blob/master/api/controllers.js#L9

**Comment by colevandersWands** [comment]
good work (and thank you) for finding this bug. I'll fix it in the template
